name: FE-Alogarithm
on:
  #监听push操作
  push:
    branches:
      # master分支，你也可以改成其他分支
      - master

jobs:
  # 任务ID
  build:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
      # 使用别人的action
      - uses: actions/checkout@v2
      # 步骤名称
      - name: yarn
        # 步骤执行指令
        run: yarn
      - name: yarn build
        run: yarn build
      # 命名这个任务为发布Deploy
      - name: Deploy
        # 因为构建之后，需要把代码上传到服务器上，所以需要连接到ssh，并且做一个拷贝操作
        uses: cross-the-world/scp-pipeline@master
        env:
          WELCOME: 'ssh scp ssh pipelines'
          LASTSSH: 'Doing something after copying'
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          connect_timeout: 10s
          branch: gh-pages
          folder: 'dist/'
